version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-instagram
    restart: always
    ports:
      # Ánh xạ cổng host 14333 -> container 1433 để tránh đụng độ cổng 1433 có sẵn trên Windows
      - "14333:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
      - MSSQL_PID=Developer
    volumes:
      - mssql_data:/var/opt/mssql
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  mssql_data:
